default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_admin_enumerize_development

test:
  <<: *default
  database: rails_admin_enumerize_test

production:
  <<: *default
  database: rails_admin_enumerize_production
  username: rails_admin_enumerize
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
